version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow-init:
    image: apache/airflow:2.6.3
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__FERNET_KEY=jKPL3Gthm0RPlr2sXxyKo1XYPvDwbG4r1xQ9zI3P4U8=
      - AIRFLOW__WEBSERVER__SECRET_KEY=efb8d9d99b7f4b1b87068d6c3d5e4c62
    entrypoint: |
      /bin/bash -c \
      "airflow db init && \
       airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins

  webserver:
    image: apache/airflow:2.6.3
    depends_on:
      - airflow-init
      - postgres
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__FERNET_KEY=jKPL3Gthm0RPlr2sXxyKo1XYPvDwbG4r1xQ9zI3P4U8=
      - AIRFLOW__WEBSERVER__SECRET_KEY=efb8d9d99b7f4b1b87068d6c3d5e4c62
    command: webserver
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins

  scheduler:
    image: apache/airflow:2.6.3
    depends_on:
      - airflow-init
      - postgres
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__FERNET_KEY=jKPL3Gthm0RPlr2sXxyKo1XYPvDwbG4r1xQ9zI3P4U8=
      - AIRFLOW__WEBSERVER__SECRET_KEY=efb8d9d99b7f4b1b87068d6c3d5e4c62
    command: scheduler
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins

volumes:
  postgres_data:
