version: '3.8'

services:
  sftp:
    image: atmoz/sftp
    volumes:
      - ./sftp-data:/home/sftpuser/upload
    ports:
      - "2222:22"
    environment:
      SFTP_USERS: "sftpuser:password:1001"

# TODO: create postgres configuration

  app:
    build:
      context: .
    depends_on:
      - sftp
    environment:
      - SFTP_HOST=sftp
      - SFTP_PORT=22
      - SFTP_USERNAME=sftpuser
      - SFTP_PASSWORD=password
      # TODO: add env to provide postgres connection info
    entrypoint: |
      /bin/sh -c \
      "while ! pg_isready -h postgres; do \
        echo 'Waiting for Airflow metadata database to be initialized...'; sleep 1; \
      done; \
      python /app.py"
    volumes:
      - ./app.py:/app.py

volumes:
  postgres_data:
