version: '3.8'

services:
  sftp:
    image: atmoz/sftp
    volumes:
      - ./sftp-data:/home/sftpuser/upload:rw
    ports:
      - "2222:22"
    environment:
      SFTP_USERS: "sftpuser:password:1001"

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"

  app:
    build:
      context: .
    depends_on:
      - sftp
      - postgres
    environment:
      - SFTP_HOST=sftp
      - SFTP_PORT=22
      - SFTP_USERNAME=sftpuser
      - SFTP_PASSWORD=password
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydatabase
    entrypoint: |
      /bin/sh -c \
      "while ! pg_isready -h postgres; do \
        echo 'Waiting for Airflow metadata database to be initialized...'; sleep 1; \
      done; \
      python /app.py"
    volumes:
      - ./app.py:/app.py

volumes:
  postgres_data:
