version: '3.8'

services:
  sftp:
    image: atmoz/sftp
    volumes:
      - ./sftp-data:/home/sftpuser/upload
    ports:
      - "2222:22"
    environment:
      SFTP_USERS: "sftpuser:password:1001"
      
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow-init:
    image: apache/airflow:2.6.3
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:postgres@postgres/mydatabase
      - AIRFLOW__CORE__FERNET_KEY=jKPL3Gthm0RPlr2sXxyKo1XYPvDwbG4r1xQ9zI3P4U8=
      - AIRFLOW__WEBSERVER__SECRET_KEY=efb8d9d99b7f4b1b87068d6c3d5e4c62
    entrypoint: |
      /bin/bash -c \
      "while ! nc -z postgres 5432; do sleep 1; done; \
      airflow db init && \
      airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins

  webserver:
    image: apache/airflow:2.6.3
    depends_on:
      - airflow-init
      - postgres
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:postgres@postgres/mydatabase
      - AIRFLOW__CORE__FERNET_KEY=jKPL3Gthm0RPlr2sXxyKo1XYPvDwbG4r1xQ9zI3P4U8=
      - AIRFLOW__WEBSERVER__SECRET_KEY=efb8d9d99b7f4b1b87068d6c3d5e4c62
    entrypoint: |
      /bin/bash -c \
      "while ! nc -z postgres 5432; do sleep 1; done; \
      while ! psql postgresql://postgres:postgres@postgres/mydatabase -c 'SELECT 1 FROM alembic_version LIMIT 1;' 2>/dev/null; do \
        echo 'Waiting for Airflow metadata database to be initialized...'; sleep 1; \
      done; \
      airflow webserver"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins

  scheduler:
    image: apache/airflow:2.6.3
    depends_on:
      - airflow-init
      - postgres
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:postgres@postgres/mydatabase
      - AIRFLOW__CORE__FERNET_KEY=jKPL3Gthm0RPlr2sXxyKo1XYPvDwbG4r1xQ9zI3P4U8=
      - AIRFLOW__WEBSERVER__SECRET_KEY=efb8d9d99b7f4b1b87068d6c3d5e4c62
    command: scheduler
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins

volumes:
  postgres_data:
